services:
  
    postgres:
      container_name: postgres-pg-vector
      image: pgvector/pgvector:pg17
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: example_db
      ports: ["5432:5432"]
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
    driver: local