services:
  
  postgres:
     container_name: postgres-pg-vector
     image: pgvector/pgvector:pg17
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: example_db
     ports: ["5432:5432"]
     volumes:
       - pg_vector_data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:2025.2
    container_name: seq-log
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: True
    restart: unless-stopped
    volumes:
      - seq_data:/data
volumes:
  pg_vector_data:
    driver: local
  seq_data:
    driver: local     